services:
  db:
    image: postgres:16.0-alpine
    container_name: db_postgres
    volumes:
      - file_sharing_postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - "5444:5432"
    expose:
      - "5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
  web:
    build:
      context: .
    expose:
      - "8000"
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - file_sharing_static_volume:/app/static
      - file_sharing_files_volume:/app/files
  nginx:
    build: nginx/.
    container_name: nginx
    ports:
      - "8025:80"
    depends_on:
      - db
      - web
    volumes:
      - file_sharing_static_volume:/home/file_sharing/web/static/

volumes:
  file_sharing_postgres_data:
  file_sharing_static_volume:
  file_sharing_files_volume: