# Generated by Django 4.2.6 on 2025-02-26 18:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_files_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=1025, verbose_name='Наименование'),
            preserve_default=False,
        ),
    ]
